development:
  server: "http://fayservermaster.herokuapp.com/faye"
  secret_token: "batkaro"
test:
  server: "https://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://fayservermaster.herokuapp.com/faye"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day